export type JobState =
  | 'queued'
  | 'running'
  | 'succeeded'
  | 'failed'
  | 'cancelled'
  | 'timed_out'
  | 'lost';

export type JobPhase =
  | 'awaiting_approval'
  | 'queued'
  | 'resolving_credentials'
  | 'connecting'
  | 'submitting'
  | 'executing'
  | 'reconnecting'
  | 'cancelling'
  | 'finalizing'
  | 'finished';

export type JobBackend = 'local' | 'ssh_direct' | 'ssh_runner' | 'github';

export type JobConnectionState =
  | 'not_applicable'
  | 'disconnected'
  | 'connecting'
  | 'connected'
  | 'reconnecting';

export type ExecutionMode = 'auto' | 'direct' | 'runner';

export type JobAdapter = 'generic' | 'training' | 'slurm' | 'apple-signing';

export interface OutputPolicy {
  mode?: 'tail' | 'full' | 'none';
  maxBytes?: number;
  retentionHours?: number;
}

export interface JobExecution {
  backend: JobBackend;
  phase: JobPhase;
  connectionState: JobConnectionState;
  durable: boolean;
  resumable: boolean;
  runnerVersion?: string;
  remoteJobId?: string;
  reconnectCount: number;
  lastEventSequence: number;
}

export interface JobPolicyStatus {
  risk: 'standard' | 'privileged' | 'credential' | 'release' | 'destructive';
  approval: 'not_required' | 'pending' | 'approved' | 'rejected' | 'expired';
  approvedAt?: string;
  grantExpiresAt?: string;
}

export type JobOutputStream = 'stdout' | 'stderr' | 'system';

export interface JobOutputChunk {
  sequence: number;
  stream: JobOutputStream;
  data: string;
  timestamp: string;
}

export interface JobProgress {
  percentage?: number;
  phase?: string;
  message?: string;
  metrics?: {
    epoch?: number;
    step?: number;
    loss?: number;
    etaSeconds?: number;
    checkpoint?: string;
    gpu?: string;
  };
  updatedAt: string;
}

export interface LifecycleAssessment {
  phase: 'waiting' | 'executing' | 'finished';
  health: 'queued' | 'active' | 'stalled' | 'terminal';
  elapsedMs: number;
  idleMs: number;
  estimatedRemainingMs?: number;
  summary: string;
}

export interface LocalJobTarget {
  kind: 'local';
}

export interface SshJobTarget {
  kind: 'ssh';
  host: string;
  port?: number;
  username: string;
  privateKeyPath?: string;
  agent?: string;
  hostKeySha256?: string;
  hostKeyAlgorithm?: string;
  allowUnverifiedHostKey?: boolean;
  runnerPath?: string;
  /** Kept in memory only and never copied to JobRecord or the persistent store. */
  password?: string;
  passphrase?: string;
}

export type JobTarget = LocalJobTarget | SshJobTarget;

export interface JobTiming {
  requestTraceId?: string;
  requestReceivedAt?: string;
  toolReceivedAt?: string;
  credentialsResolvedAt?: string;
  commandStartedAt?: string;
  sshReadyAt?: string;
  firstOutputAt?: string;
  policyResolvedAt?: string;
  runnerAcceptedAt?: string;
  disconnectedAt?: string;
  recoveredAt?: string;
}

export interface StartJobInput {
  command: string;
  /** Stable caller-provided key that prevents duplicate starts after retries. */
  idempotencyKey?: string;
  args?: string[];
  cwd?: string;
  env?: Record<string, string>;
  shell?: boolean;
  label?: string;
  timeoutMs?: number;
  target?: JobTarget;
  /** RE2-compatible expression whose first capture group is the percentage. */
  progressPattern?: string;
  executionMode?: ExecutionMode;
  requireDurable?: boolean;
  adapter?: JobAdapter;
  outputPolicy?: OutputPolicy;
  eventSubscriptions?: string[];
  /** Internal safe reference used to recover durable Runner jobs. */
  credentialProfileId?: string;
  metadata?: Record<string, unknown>;
  /** Safe lifecycle timestamps generated by RunBeacon integrations. */
  timing?: JobTiming;
}

export interface PublicJobTarget {
  kind: 'local' | 'ssh';
  host?: string;
  port?: number;
  username?: string;
  verifiedHostKey?: boolean;
  hostKeySha256?: string;
  hostKeyAlgorithm?: string;
  runnerPath?: string;
}

export interface JobRecord {
  id: string;
  idempotencyKey?: string;
  label: string;
  displayCommand: string;
  target: PublicJobTarget;
  state: JobState;
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  updatedAt: string;
  version: number;
  pid?: number;
  exitCode?: number | null;
  signal?: string | null;
  error?: string;
  cancelRequested?: boolean;
  cancellationVerified?: boolean;
  progress?: JobProgress;
  lastOutputAt?: string;
  lastProgressAt?: string;
  timing?: JobTiming;
  execution: JobExecution;
  policy: JobPolicyStatus;
  adapter: JobAdapter;
  outputPolicy: Required<OutputPolicy>;
  eventSubscriptions?: string[];
  credentialProfileId?: string;
  progressPattern?: string;
  output: JobOutputChunk[];
  outputBytes: number;
  outputLines: number;
  outputTruncated: boolean;
  metadata?: Record<string, unknown>;
}

export interface JobSnapshot extends Omit<JobRecord, 'output'> {
  tail: JobOutputChunk[];
  assessment: LifecycleAssessment;
}

export interface WaitResult {
  timedOut: boolean;
  job: JobSnapshot;
}

export interface WatchResult {
  changed: boolean;
  job: JobSnapshot;
}

export const TERMINAL_JOB_STATES = new Set<JobState>([
  'succeeded',
  'failed',
  'cancelled',
  'timed_out',
  'lost',
]);

export function isTerminalJobState(state: JobState): boolean {
  return TERMINAL_JOB_STATES.has(state);
}
